export const description = {
  title: "Welcome to the configuration page",
  // For internal audits when no config saved
  subtitleNone: "Please fill out the configuration fields below.",
  jiraSubtitle: "-- Jira Fields --",
  databaseSubtitle: "--Database Fields--",
  databaseClassesSubtitle: "--Database Classes & Attributes Fields--",
  // --> Jira
  privateKeyLabel: "Private Key (Jira): ",
  consumerKeyLabel: "Consumer Key (Jira): ",
  consumerKeyPlaceholder: "Enter the Jira Consumer Key",
  tokenLabel: "Token (Jira): ",
  tokenPlaceholder: "Enter the Jira Token",
  tokenSecretLabel: "Token Secret (Jira)",
  tokenSecretPlaceholder: "Enter the Jira Token Secret",
  signatureMethodLabel: "Signature Method (Jira - oAuth):",
  signatureMethodOption: "RSA-SHA1",
  jiraurlLabel: "Jira URL:",
  jiraurlPlaceholder: "Enter the Jira URL",
  jiraportLabel: "Jira Port: ",
  jiraportPlaceholder: "Enter the Jira Port",
  backupProjectLabel: "Backup Project Key (Jira)",
  backupProjectPlaceholder: "Enter the Backup Project Key",
  restorationProjectLabel: "Restoration Project Key (Jira)",
  restorationProjectPlaceholder: "Enter the Restoration Project Key",
  errorProjectLabel: "Error Project Key (Jira)",
  errorProjectPlaceholder: "Enter the Error Project Key",
  changeProjectLabel: "Change Project Key (Jira)",
  changeProjectPlaceholder: "Enter the Change Project Key",
  // --> Database Fields
  dbtypeLabel: "Database Type: ",
  dbtypeOption: "MariaDB",
  dbhostLabel: "Database Host: ",
  dbhostPlaceholder: "Enter the Database Host",
  dbportLabel: "Database Port:",
  dbportPlaceholder: "Enter the Database Port",
  dbuserLabel: "Database Audit User: ",
  dbuserPlaceholder: "Enter the Database Audit User",
  dbuserpasswordLabel: "Database Audit Password",
  dbuserpasswordPlaceholder: "Enter the Database Audit Password",
  // --> Database Classes & Attributes
  // * Logs
  logsClassNameLabel: "Logs Name (Database):",
  logsClassNamePlaceholder: "Enter the Logs Class Name",
  logsLogIDLabel: "Logs - ID Name: ",
  logsLogIDPlaceholder: "Enter the ID Name for Logs",
  logsProjectKeyLabel: "Logs - Project Key (Name):",
  logsProjectKeyPlaceholder:
    "Enter the Project Key (Jira) Name Attibute saved in Logs",
  logsTicketKeyLabel: "Logs - Ticket Key (Name): ",
  logsTicketKeyPlaceholder: "Enter the Ticket Key (Jira)",
  logsTypeLabel: "Logs - Type (Name):",
  logsTypePlaceholder: "Enter the Type Name for Logs",
  // * User
  userClassNameLabel: "User Name (Database):",
  userClassNamePlaceholder: "Enter the User Class Name",
  userUserIdLabel: "User ID (Name):",
  userUserIdPlaceholder: "Enter the User ID Attribute Name",
  userFirstnameLabel: "User First Name (Name):",
  userFirstnamePlaceholder: "Enter the User First Name (Attribute Name)",
  userLastnameLabel: "User Last Name (Name):",
  userLastnamePlaceholder: "Enter the User Last Name (Attribute Name)",
  userEmailLabel: "User Email (Name):",
  userEmailPlaceholder: "Enter the User Email (Attribute Name)",
  userPasswordLabel: "User Password (Name):",
  userPasswordPlaceholder: "Enter the User Password (Attribute Name)",
  userUsergroupIdLabel: "User User-Group ID (Name):",
  userUsergroupIdPlaceholder: "Enter the User User Group (Attribute Name)",
  userTitleLabel: "User Job-Title / Position (Name):",
  userTitlePlaceholder: "Enter the User Job-Title/Position (Attribute Name)",
  // * User Group
  usergroupClassNameLabel: "User Group Name (Database):",
  usergroupClassNamePlaceholder: "Enter the User Group Class Name",
  usergroupGroupIdLabel: "User Group ID (Name):",
  usergroupGroupIdPlaceholder: "Enter the User Group ID (Attribute Name)",
  usergroupReadRightsLabel: "User Group Read Rights (Name):",
  usergroupReadRightsPlaceholder:
    "Enter the User Group Read Rights (Attribute Name)",
  usergroupDeleteRightsLabel: "User Group Delete Rights (Name):",
  usergroupDeleteRightsPlaceholder:
    "Enter the User Group Delete Rights (Attribute Name)",
  usergroupCreateRightsLabel: "User Group Create Rights (Name):",
  usergroupCreateRightsPlaceholder:
    "Enter the User Group Create Rights (Attribute Name",
  usergroupUpdateRightsLabel: "User Group Update Rights (Name):",
  usergroupUpdateRightsPlaceholder:
    "Enter the User Group Update Rights (Attribute Name)",
  usergroupGroupNameLabel: "User Group Group-Name (Name):",
  usergroupGroupNamePlaceholder:
    "Enter the User Group Group-Name (Attribute Name)",
  // * Form Input Values
  namePrivatekey: "privatekey",
  nameConsumerKey: "consumerkey",
  nameToken: "token",
  nameTokenSecret: "tokensecret",
  nameSignatureMethod: "signaturemethod",
  nameJiraUrl: "jiraurl",
  nameJiraPort: "jiraport",
  nameBackup: "backup",
  nameRestoration: "restoration",
  nameError: "error",
  nameChange: "change",
  nameDbType: "dbtype",
  nameDbHost: "dbhost",
  nameDbPort: "dbport",
  nameDbUsername: "dbusername",
  nameDbPassword: "dbpassword",
  nameLogs: "logs",
  nameLogsLogsId: "logsid",
  nameLogsProjectKey: "projectkey",
  nameLogsTicketKey: "ticketkey",
  nameLogsType: "logstype",
  nameUser: "user",
  nameUserUserId: "userid",
  nameUserFirstName: "firstname",
  nameUserLastName: "lastname",
  nameUserEmail: "email",
  nameUserPassword: "password",
  nameUserUserGroupId: "usergroupid",
  nameUserTitle: "title",
  nameUserGroups: "usergroups",
  nameUserGroupsGroupId: "usergroupsgroupid",
  nameUserGroupsReadRights: "readrights",
  nameUserGroupsDeleteRights: "deleterights",
  nameUserGroupsCreateRights: "createrights",
  nameUserGroupsUpdateRights: "updaterights",
  nameUserGroupsGroupName: "groupname",
  // * Form - Error Messages
  errorPrivatekey: "Please enter the private key",
  errorConsumerKey: "Please enter the consumer key",
  errorToken: "Please enter the token",
  errorTokenSecret: "Please enter the token secret",
  errorSignatureMethod: "Please enter the signature method",
  errorJiraUrl: "Please enter the Jira url",
  errorJiraPort: "Please enter the Jira port",
  errorBackup: "Please enter the Backup project key",
  errorRestoration: "Please enter the Restoration project key",
  errorError: "Please enter the Error project key",
  errorChange: "Please enter the Change project key",
  errorDbType: "Please select the database type",
  errorDbHost: "PLease enter the database host",
  errorDbPort: "Please enter the database port",
  errorDbUserName: "Please enter the database username",
  errorDbPassword: "Please enter the database password",
  errorLogs: "Please enter the Logs Class Name",
  errorLogsLogsId: "Please enter the Logs ID Attribute Name",
  errorLogsProjectKey: "Please enter the Project Key Attribute Name",
  errorLogsTicketKey: "Please enter the Ticket Key Attribute Name",
  errorLogsType: "Please enter the Logs-Type Attribute Name",
  errorUser: "Please enter the User Class Name",
  errorUserUserId: "Please enter the User ID Attribute Name",
  errorUserFirstname: "Please enter the First Name Attribute Name",
  errorUserLastname: "Please enter the Last Name Attribute Name",
  errorUserEmail: "Please enter the Email Attribute Name",
  errorUserPassword: "Please enter the Password Attribute Name",
  errorUserUserGroupId: "Please enter the User Group Attribute Name (FK)",
  errorUserTitle: "Please enter the Job-Title/Position Attribute Name",
  errorUserGroups: "Please enter the User Groups Class Name",
  errorUserGroupsGroupId:
    "Please enter the User Groups Group Id Attribute Name",
  errorUserGroupsReadRights: "Please enter the Read Rights Attribute Name",
  errorUserGroupsDeleteRights: "Please enter the Delete Rights Attribute Name",
  errorUserGroupsCreateRights: "Please enter the Create Rights Attribute Name",
  errorUserGroupsUpdateRights: "Please enter the Update Rights Attribute Name",
  errorUserGroupsGroupName: "Please enter the Group Name Attribute Name",
  // --> Other Placeholders
  loading: "Configuration status is loading...",
  // For internal audits when config saved
};
