export const description = {
  title: "Add new user",
  email: "Email: ",
  emailmsg: "Please enter the users email",
  password: "Password: ",
  passwordmsg: "Please enter the users password",
  companyname: "Company name: ",
  companynamemsg: "Please enter the companies name",
  type: "Type:",
  internalValue: "internal",
  internalText: "Internal Auditor",
  externalValue: "external",
  externalText: "External Auditor",
  apistatusmsg: "E-Mail already in use!",
  useridmsg: "The user has been added, and his folder id is",
  externalstatusmsg: "The external user has been added!",
};
